[app]
name = "Random Nick"
menu = "Badge"

[entry]
class = "RandomNickApp"

[metadata]
author = "Flow3r Badge Authors & strifel"
license = "LGPL-3.0-only"
url = "https://github.com/strifel/random-nick"
version = 1